#!/usr/bin/env python3
"""Assemble the output skill folder from generated content.

Usage: package_skill.py <output-dir>
                       --skill-md <path>
                       --schemas <path>
                       --script-stubs <path-to-spec.json>
Output: Writes files. Prints the absolute output directory path on stdout.
Exit codes:
  0 on success
  1 on invalid input or write error

stdlib only.
"""
import argparse
import json
import os
import sys
from pathlib import Path


STUB_TEMPLATE = '''#!/usr/bin/env python3
"""{purpose}

Invocation: {invocation}

Output: JSON to stdout (per contract below).
Exit codes: {exit_codes}

This is a stub generated by skill-distiller. Implement against the real
artifacts the converted skill will operate on. Validate output against the
contract in schemas.md.

OUTPUT CONTRACT (JSON Schema draft-07):
{schema}
"""
import json
import sys


def main():
    raise NotImplementedError(
        "Stub generated by skill-distiller. See docstring for the contract."
    )


if __name__ == "__main__":
    sys.exit(main())
'''


IMPL_NOTES = """# Implementation Notes

This skill folder was generated by `skill-distiller`. The scripts in `scripts/`
contain working implementations generated from the original skill's embedded
commands and workflow description.

## Next steps

1. Read `SKILL.md` for the orchestration sequence and the points where LLM
   judgment is required.
2. Read `schemas.md` for the JSON Schema contracts each script must satisfy.
3. Test each script individually against real inputs to verify correctness.
4. Run the skill end-to-end against a known input and verify the output
   matches expectations.
5. Review and adjust the generated code for domain-specific edge cases.

## Constraints

- Scripts emit a single JSON value on stdout. Use stderr for logs.
- Non-zero exit terminates the workflow. Use exit codes meaningfully.
- Prefer stdlib over external dependencies. Where an external library is
  necessary (e.g., `packaging` for semver), document it at the top of the
  script.
"""


def write_script(scripts_dir, script_spec):
    name = script_spec["name"]
    code = script_spec.get("code", "").strip()

    if code:
        body = code + "\n"
    else:
        body = STUB_TEMPLATE.format(
            purpose=script_spec.get("purpose", ""),
            invocation=script_spec.get("invocation", name),
            exit_codes=script_spec.get("exit_codes", "0 on success"),
            schema=json.dumps(script_spec.get("output_schema", {}), indent=2),
        )

    path = scripts_dir / name
    path.write_text(body, encoding="utf-8")
    try:
        os.chmod(path, 0o755)
    except OSError:
        pass


def main():
    p = argparse.ArgumentParser(description="Package a distilled skill folder.")
    p.add_argument("output_dir")
    p.add_argument("--skill-md", required=True)
    p.add_argument("--schemas", required=True)
    p.add_argument("--script-stubs", required=True,
                   help="Path to spec JSON describing scripts to stub out.")
    p.add_argument("--critique",
                   help="Path to CRITIQUE.md to include in the output.")
    args = p.parse_args()

    out = Path(args.output_dir)
    try:
        out.mkdir(parents=True, exist_ok=True)
        (out / "scripts").mkdir(exist_ok=True)
    except OSError as e:
        print(f"error creating output directory: {e}", file=sys.stderr)
        return 1

    critique_text = None
    try:
        skill_md = Path(args.skill_md).read_text(encoding="utf-8")
        schemas = Path(args.schemas).read_text(encoding="utf-8")
        stubs_spec = json.loads(Path(args.script_stubs).read_text(encoding="utf-8"))
        if args.critique:
            critique_text = Path(args.critique).read_text(encoding="utf-8")
    except (OSError, json.JSONDecodeError) as e:
        print(f"error reading input: {e}", file=sys.stderr)
        return 1

    try:
        (out / "SKILL.md").write_text(skill_md, encoding="utf-8")
        (out / "schemas.md").write_text(schemas, encoding="utf-8")
        (out / "IMPLEMENTATION.md").write_text(IMPL_NOTES, encoding="utf-8")
        if critique_text:
            (out / "CRITIQUE.md").write_text(critique_text, encoding="utf-8")
        for s in stubs_spec.get("scripts", []):
            if "name" not in s:
                continue
            write_script(out / "scripts", s)
    except OSError as e:
        print(f"error writing output files: {e}", file=sys.stderr)
        return 1

    print(str(out.resolve()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
